[book]
title = "The Parsec Book"
authors = ["Adam Parco <adam.parco@docker.com>",
           "Sabree Blackmon <sabree.blackmon@docker.com>",
           "Hugues de Valon <hugues.devalon@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Justin Cormack <justin.cormack@docker.com>",
           "Paul Howard <paul.howard@arm.com>"]
language = "en"
multilingual = false
src = "src"
