name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build book
      run: mdbook build

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create a Go workspace and install vmdfmt
      run: |
          mkdir /tmp/go
          export GOPATH=/tmp/go
          go get github.com/bobertlo/vmd/cmd/vmdfmt
    - name: Install markdown-link-check tool
      run: npm install markdown-link-check
    - name: Check formatting
      run: |
          export PATH="$PATH:/tmp/go/bin:$(pwd)/node_modules/.bin"
          ./ci/check_format.sh
